### ISSUE TITLE
`ValueError: unknown test id`

### ISSUE THREAD

**Issue by jrbourbeau** [xarray-contrib/issue-from-pytest-log#14]
We're getting the following error over in `dask/dask` in [this CI build](https://github.com/dask/dask/actions/runs/3962073914/jobs/6788284048)

```python
 Parsing logs ...
Traceback (most recent call last):
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.5/parse_logs.py", line 220, in <module>
    preformatted = [preformat_report(report) for report in failed]
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.5/parse_logs.py", line 220, in <listcomp>
    preformatted = [preformat_report(report) for report in failed]
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.5/parse_logs.py", line 101, in _
    parsed = parse_nodeid(report.nodeid)
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.5/parse_logs.py", line 75, in parse_nodeid
    raise ValueError(f"unknown test id: {nodeid}")
ValueError: unknown test id: dask/array/tests/test_stats.py
```

I should also note that we're using the latest `1.2.5` release of `xarray-contrib/issue-from-pytest-log`. Happy to provide any additional context that's needed.

**Comment by keewis** [comment]
I just released a new version, but as I mentioned in the PR I can't reproduce locally and thus can't be entirely sure this actually fixed the issue. In case you're still seeing this feel free to reopen.

**Comment by jrbourbeau** [comment]
Thanks @keewis! Updating to 1.2.6 over in https://github.com/dask/dask/pull/9865

**Comment by jrbourbeau** [comment]
Fixed! Thanks again @keewis
